hmrc/help-to-save-frontend

app/uk/gov/hmrc/helptosavefrontend/config/frontendGlobal.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/SessionCacheConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/IvController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/StartPagesController.scala, app/uk/gov/hmrc/helptosavefrontend/models/HTSSession.scala, app/uk/gov/hmrc/helptosavefrontend/views/core/about_help_to_save.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/core/apply_help_to_save.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/core/eligibility_help_to_save.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/helpers/start_nav.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/failure/user_aborted_or_incomplete.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/main_template.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/declaration.scala.html, conf/app.routes, conf/application.conf, project/FrontendBuild.scala, test/uk/gov/hmrc/helptosavefrontend/NotEligiblePageSpec.scala, test/uk/gov/hmrc/helptosavefrontend/config/SessionFilterSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/IvControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterSpec.scala
added in session filter and caching api
Changed desscibesion
=> WIP key store set up

app/uk/gov/hmrc/helptosavefrontend/models/NSIUserInfo.scala, test/uk/gov/hmrc/helptosavefrontend/models/NSIUserInfoSpec.scala
updated validation checks as per https://docs.google.com/document/d/1pwP94ZMzgMC1DZh4ykumYd2QRkB-54pNYTm93rCvWC4/edit
=> Updated NSI validation checks

app/uk/gov/hmrc/helptosavefrontend/util/Logging.scala
```
[error] /home/suresh/workspace/help-to-save-frontend/app/uk/gov/hmrc/helptosavefrontend/util/Logging.scala:22: '.' expected but ']' found.
[error]   val logger = Logger(classOf[this])
[error]                                   ^
[error] /home/suresh/workspace/help-to-save-frontend/app/uk/gov/hmrc/helptosavefrontend/util/Logging.scala:24: identifier expected but '}' found.
[error] }
[error] ^
[error] two errors found
```
=> Fix breaking build

app/uk/gov/hmrc/helptosavefrontend/connectors/IvConnector.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/SessionCacheConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EnrolmentCheckBehaviour.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/IntroductionController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/SessionBehaviour.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/UpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/models/EligibilityCheckError.scala, app/uk/gov/hmrc/helptosavefrontend/models/HTSSession.scala, app/uk/gov/hmrc/helptosavefrontend/util/package.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/SessionCacheConnectorImplSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EnrolmentAndEligibilityCheckBehaviour.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/UpdateEmailAddressControllerSpec.scala
already gone through the eligibility checks
=> Checks are made to see if user is already enrolled and if user has

app/uk/gov/hmrc/helptosavefrontend/config/FrontendWiring.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/NSIConnector.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/NSIConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HTS-489
=> HTS-489 change update email addresss POST to PUT

app/uk/gov/hmrc/helptosavefrontend/controllers/AccessAccountController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveAuth.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/IntroductionController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/IvController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/AccountHolderUpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/metrics/Metrics.scala, app/uk/gov/hmrc/helptosavefrontend/util/Toggles.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/AccessAccountControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EnrolmentAndEligibilityCheckBehaviour.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveAuthSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/IntroductionControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/AccountHolderUpdateEmailAddressControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressControllerSpec.scala
Got rid of unused parameters in test
=> Added additional time logging

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/NSIConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveAuth.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/AccountHolderUpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/VerifyEmailBehaviour.scala, app/uk/gov/hmrc/helptosavefrontend/models/HTSEvent.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/NSIConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/AccountHolderUpdateEmailAddressControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/HTSEventSpec.scala
```
[info] Statement coverage.: 92.88%
[info] Branch coverage....: 100.00%
[info] Coverage reports completed
[info] Coverage is above minimum [92.88% > 92.0%]
[info] All done. Coverage was [92.88%]
```
=> HTS-502: TxM: adjust Splunk logging following TxM/HtS London session

app/uk/gov/hmrc/helptosavefrontend/config/FrontendGlobal.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/AccessAccountController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EnrolmentCheckBehaviour.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveAuth.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/SessionBehaviour.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/AccountHolderUpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/email/VerifyEmailBehaviour.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/AccessAccountControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/AuthSupport.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EnrolmentAndEligibilityCheckBehaviour.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveAuthSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/NSIControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/AccountHolderUpdateEmailAddressControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/views/register/CheckYourEmailSpec.scala, test/uk/gov/hmrc/helptosavefrontend/views/register/EmailVerifyErrorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/views/register/UpdateEmailViewSpec.scala, test/uk/gov/hmrc/helptosavefrontend/views/register/ViewBehavioursSpec.scala
=> refactored HtSContext to include non-optional NINO

app/uk/gov/hmrc/helptosavefrontend/controllers/HelpToSaveAuth.scala, app/uk/gov/hmrc/helptosavefrontend/util/Logging.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/NSIConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/AuthSupport.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/AccountHolderUpdateEmailAddressControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/email/NewApplicantUpdateEmailAddressControllerSpec.scala
coverage is now at 97%
```
Statement coverage.: 97.08%
[info] Branch coverage....: 95.83%
[info] Coverage reports completed
[info] Coverage is above minimum [97.08% > 92.0%]
[info] All done. Coverage was [97.08%]
```
=> increased test coverage

app/uk/gov/hmrc/helptosavefrontend/models/userinfo/UserInfo.scala, app/uk/gov/hmrc/helptosavefrontend/views/register/check_your_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/create_account_help_to_save.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/email_updated.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/select_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/you_are_eligible.scala.html, conf/application.conf, conf/messages
Formatting, alignment, spacing and copy amends to the create account process.
=> HTS-65 - Frontend styling/formatting on create account

app/uk/gov/hmrc/helptosavefrontend/views/confirm_check_eligibility.scala.html, conf/application.conf, conf/messages
Update content on No Account page
=> Hts 420 no account

app/uk/gov/hmrc/helptosavefrontend/views/helpers/input_text.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/check_your_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/give_email.scala.html
Remove bold from form labels and fix main heading size/weight
=> HTS-460 Remove bold copy from form labels, use correct h1 size/weight

app/uk/gov/hmrc/helptosavefrontend/views/register/daily_cap_reached.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/total_cap_reached.scala.html, conf/app.routes, conf/messages
Updates content and URL for the daily and total account cap pages
=> Hts 443 account checking cap

app/uk/gov/hmrc/helptosavefrontend/views/register/cannot_change_email_try_later.scala.html, conf/messages
Update layout for cannot change email pages.
=> HTS-589 Content and format for cannot change email try later

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, conf/app.routes
=> Hts 605 update urls

app/uk/gov/hmrc/helptosavefrontend/views/core/not_eligible.scala.html, conf/messages
Adds link to eligibility page in the introduction from the Not Eligible to Create and Account page
=> HTS-548 Adds eligibility link from illegible page

app/uk/gov/hmrc/helptosavefrontend/controllers/NewApplicantUpdateEmailAddressController.scala, app/uk/gov/hmrc/helptosavefrontend/views/register/cannot_change_email.scala.html, conf/messages, test/uk/gov/hmrc/helptosavefrontend/controllers/NewApplicantUpdateEmailAddressControllerSpec.scala
Handles empty submit and updates content for Cannot Change Email Address page.
=> Hts 589 handle empty submit

app/uk/gov/hmrc/helptosavefrontend/views/email/check_your_email.scala.html, conf/messages
Updates copy for Email Verification page for existing users
=> HTS-632 Update copy for existing user verify email

app/uk/gov/hmrc/helptosavefrontend/views/register/details_are_incorrect.scala.html, conf/app.routes, conf/messages
Adds copy and format for incorrect details page
=> HTS-611 Copy and format for incorrect details page

app/uk/gov/hmrc/helptosavefrontend/views/confirm_check_eligibility.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/core/cannot_change_email_try_later.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/core/privacy.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/email/check_your_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/email/update_email_address.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/introduction/navigation.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/failed_iv.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/failed_matching.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/insufficient_evidence.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/iv_success.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/locked_out.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/precondition_failed.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/technical_iv_issues.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/time_out.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/user_aborted.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/cannot_change_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/check_your_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/create_account_help_to_save.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/daily_cap_reached.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/details_are_incorrect.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/give_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/missing_user_info.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/select_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/total_cap_reached.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/you_are_eligible.scala.html
Global update of page heading sizing from xlarge to large
=> HTS-639 Update main heading sizeing xlarge to large

app/uk/gov/hmrc/helptosavefrontend/views/confirm_check_eligibility.scala.html
Increases first paragraph type size
=> HTS-420 Add lede class to increase first paragraph size

app/uk/gov/hmrc/helptosavefrontend/views/introduction/how_we_calculate_bonuses.scala.html, conf/messages
Updates the copy in the introduction for how we calculate bonuses - how withdrawals will affect bonus amounts.
=> HTS-641 Update intro copy outlining withdrawals affect on bonuses

app/uk/gov/hmrc/helptosavefrontend/views/register/create_account_error.scala.html
Update create account error main heading size.
=> Adjust create account error h1 sizing

conf/messages
Update the heading, copy and terms on the You Are Eligible page
=> HTS-646 Update you are eligible copy/terms

app/uk/gov/hmrc/helptosavefrontend/views/register/create_account_help_to_save.scala.html, conf/messages
Update copy on create account page
=> Hts 642 update create account copy

app/uk/gov/hmrc/helptosavefrontend/views/confirm_check_eligibility.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/core/cannot_change_email_try_later.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/email/we_updated_your_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/introduction/apply.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/failed_iv.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/failed_matching.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/iv_success.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/locked_out.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/precondition_failed.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/technical_iv_issues.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/time_out.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/user_aborted.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/check_your_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/create_account_error.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/create_account_help_to_save.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/daily_cap_reached.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/email_updated.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/total_cap_reached.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/you_are_eligible.scala.html
Update spacing between content and cta buttons/links
=> HTS-640 Update spacing between content and cta buttons/links

app/uk/gov/hmrc/helptosavefrontend/controllers/EmailController.scala
https://kibana.tools.production.tax.service.gov.uk/goto/a73a195de886148f1eb8b175f6c37067
=> Remove confusing log line during select email flow

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/helptosavefrontend/views/core/confirm_check_eligibility.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/locked_out.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/iv/precondition_failed.scala.html, conf/messages
This reverts commit dd372729784318c22e784fd96840a80f4a021732.
This reverts commit 2ef692957facff19402950bcd3a8cb08471fac66.
This reverts commit 564fb6c500e840402dd0f477cd5319d066ceeb27.
=> Revert HTS-1237

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/helptosavefrontend/views/core/confirm_check_eligibility.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/not_eligible.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/think_you_are_eligible.scala.html, conf/application.conf, conf/messages
HTS-1237 updated exit link on confirm_check_eligibility page (#625)
=> HTS-1237 Updated content on no account page (#623)

test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/TestData.scala
… content on agree with conditions page
=> HTS-1274: Added unit tests to check dynamic content on agree with conditions page

app/uk/gov/hmrc/helptosavefrontend/connectors/BarsConnector.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/EmailVerificationConnector.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveConnector.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/IvConnector.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/SessionCacheConnector.scala, app/uk/gov/hmrc/helptosavefrontend/http/HttpClient.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/HttpSupport.scala
This reverts commit e8c7bb25ac8a7696e74b5679de9f12f4a172c33c.
=> HTS-1386: Don't disable implicit auditing

app/uk/gov/hmrc/helptosavefrontend/forms/BankDetailsValidation.scala, test/uk/gov/hmrc/helptosavefrontend/forms/BankDetailsValidationSpec.scala
This reverts commit 440c2edc8099b81459885802b8df133c388e9000.
=> Revert "HTS-1383: Do not remove spaces in roll numbers (#698)"

README.md, app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/IvController.scala, app/uk/gov/hmrc/helptosavefrontend/views/iv/failed_matching.scala.html, conf/app.routes, conf/application.conf, test/uk/gov/hmrc/helptosavefrontend/controllers/IvControllerSpec.scala
This reverts commit 58a958fe502f50da262330f7d27861bddc657bd6.
=> Revert "Dls 644 b (#815)"

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, build.sbt, project/plugins.sbt
DLS-1382 Update config to correct gg sign-in continue URL
=> DLS-1382 Update config to correct gg sign-in continue URL

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/forms/ReminderForm.scala, app/uk/gov/hmrc/helptosavefrontend/forms/ReminderFrequencyValidation.scala, app/uk/gov/hmrc/helptosavefrontend/models/reminder/ReminderFrequency.scala, app/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderService.scala, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_confirmation.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_set.scala.html, conf/app.routes, conf/application.conf, conf/messages, project/AppDependencies.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/forms/ReminderFrequencyValidationSpec.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderServiceSpec.scala
This is to replace [PR #840](https://github.com/hmrc/help-to-save-frontend/pull/840)
=> DLS-1868 Manually rebase branch DLS-1868 onto master

app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala
=> DLS-1982 optInStatus in the schedule record is set to false where as it should be true

app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderServiceSpec.scala
'for' comprehension replaced with multiple folds and flatMap
=> DLS-1854 for comprehension replaced with multiple folds and flatMap

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/models/reminder/ReminderFrequency.scala, app/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderService.scala, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_cancel_confirmation.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_dashboard.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_change.scala.html, conf/app.routes, conf/messages, test/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderServiceSpec.scala
rebased all previous changes into this branch as getting lot complicates to resolve in previous branch
=> DLS-1984 Create front end for HTS reminders settings - Change or cancel reminders

app/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EmailController.scala, app/uk/gov/hmrc/helptosavefrontend/models/reminder/ReminderFrequency.scala, app/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderService.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EmailControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderServiceSpec.scala
- frontend
Changes Implemented
=> DLS-1991 Update HTS reminder email database when users change email address

app/uk/gov/hmrc/helptosavefrontend/controllers/EmailController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/models/reminder/ReminderFrequency.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EmailControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderServiceSpec.scala
=> DLS-2039 Add last name to HTS reminder email

app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_cancel_confirmation.scala.html
=> DLS-2052 HTS Reminders - Cancel confirmation page shows wrong text under what happens next

app/uk/gov/hmrc/helptosavefrontend/views/register/account_created.scala.html, conf/messages
=> DLS-1887 Create front end for HTS reminders- "Account Created" page

conf/app.routes
=> DLS-2059 Update frontend URLs for HTS reminders service pages

conf/application.conf
assets front end upgrade to 3.11.0
=> DLS-1938 HTS reminders service- accessibility audit

app/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnector.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnectorSpec.scala
endpoint has been updated as per remainer change
=> DLS-remainderURLUpdate

app/uk/gov/hmrc/helptosavefrontend/views/register/create_account.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_change.scala.html
=> DLS-1938-Accessibility Check Report

app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/views/reminder/email_savings_reminders.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_cancel_confirmation.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_confirmation.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_set.scala.html, conf/app.routes, conf/messages, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala
2279 also implemented under this PR
=> DLS-2278 HTS reminders- front end changes- "Email savings reminders"

app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_change.scala.html
"Select when you want to receive reminders" (pre- selection)
Changes implemented
=> DLS-2282 HTS reminders- front end changes- 

app/uk/gov/hmrc/helptosavefrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/forms/BankDetailsValidation.scala, app/uk/gov/hmrc/helptosavefrontend/forms/ReminderFrequencyValidation.scala, app/uk/gov/hmrc/helptosavefrontend/views/reminder/email_savings_reminders.scala.html, build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/uk/gov/hmrc/helptosavefrontend/auth/HelpToSaveAuthSpec.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/HttpSupport.scala, test/uk/gov/hmrc/helptosavefrontend/forms/EmailValidationSpec.scala, test/uk/gov/hmrc/helptosavefrontend/forms/ReminderFrequencyValidationSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/HTSSessionSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/NSIPayloadSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/UserDetailsSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/account/AccountSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/eligibility/EligibilityReasonSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/eligibility/IneligibilityTypeSpec.scala, test/uk/gov/hmrc/helptosavefrontend/util/NINOLogMessageTransformerImplSpec.scala, test/uk/gov/hmrc/helptosavefrontend/util/UnitSpec.scala
Note that GitHub has struggled comparing EligibilityCheckController, it is the re-layout https://github.com/hmrc/help-to-save-frontend/commit/c8a32a67a22a14b10c6ffd874c1ea4a907d474f5 that has caused that.  The only other change to that file is this one liner: https://github.com/hmrc/help-to-save-frontend/commit/e1e96bfb0effc4616d4d80f08e76c0c76f05dba6 .
=> Dave/dls 1382/updates etc

app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/views/reminder/apply_savings_reminders.scala.html, conf/app.routes, conf/messages, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala
=> DLS-2340 HTS Reminders - Registration - Add a new page asking whether  reminders are needed

app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_set.scala.html, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala
for Reminders date from check-answers page should always take back to reminders selection first page
=> DLS-2457 HTS Reminders - Change link

conf/application.conf
Added service in URL to use new version of feedback service
=> HTS-2352 Feedback survey – old version still being accessed

app/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/models/reminder/ReminderFrequency.scala, app/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderService.scala, test/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnectorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderServiceSpec.scala
Fix for missing daysToReceive empty value
=> DLS-IntTestFix

app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala
HtsUserCreatedEvent added for Registration process
=> DLS-3839 HtsUserCreatedEvent added for Registration process

app/uk/gov/hmrc/helptosavefrontend/controllers/RegisterController.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala
=> Revert "HtsUserCreatedEvent added for Registration process"

app/uk/gov/hmrc/helptosavefrontend/config/AllowListFilter.scala, app/uk/gov/hmrc/helptosavefrontend/config/Filters.scala, conf/application.conf, project/AppDependencies.scala, test/uk/gov/hmrc/helptosavefrontend/config/FiltersSpec.scala
Replacing whitelist with allowlist
=> DLS-4193 Replacing whitelist occurances with allowlist 

app/uk/gov/hmrc/helptosavefrontend/views/accessibility/accessibility_statement.scala.html, conf/messages, conf/messages.cy
=> DLS-5246 - Update HTS accessibility statement

conf/messages.cy
Updated the Welsh versions of the monarch gender.
=> Tom/DLS-6518 - HTS - Changing 'Her Majesty's Revenue and Customs' to "His Majesty's Revenue and Customs"

app/uk/gov/hmrc/helptosavefrontend/views/core/privacy.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/layout.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/you_are_eligible.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/apply_savings_reminders.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_set.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/time_out.scala.html
…probs link - also headings in reminders and eligibility page
=> [DLS-6858] Layout template work to include sign out, service name, Welsh toggle and tech help link

app/uk/gov/hmrc/helptosavefrontend/views/email/select_email.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/apply_savings_reminders.scala.html
This is the last of the original pages on the ticket and means we should be able to move DLS-5176 into QA
=> [DLS-5176] select email and reminders pages

app/uk/gov/hmrc/helptosavefrontend/views/helpers/FormErrorMessage.scala, app/uk/gov/hmrc/helptosavefrontend/views/helpers/button.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/helpers/ga_submit_button.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/register/BankDetailsErrors.scala, app/uk/gov/hmrc/helptosavefrontend/views/register/bank_account_details.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/email_savings_reminders.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_cancel_confirmation.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_confirmation.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/reminder/reminder_frequency_set.scala.html, conf/messages, conf/messages.cy
Team wanted these extra pages upgraded as part of this ticket plus fixes for Acceptance Test selectors
=> [DLS-5176] bank details and email reminders page plus AT selectors

app/uk/gov/hmrc/helptosavefrontend/audit/HTSAuditor.scala, app/uk/gov/hmrc/helptosavefrontend/connectors/HelpToSaveReminderConnector.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/EmailController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/IntroductionController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/IvController.scala, app/uk/gov/hmrc/helptosavefrontend/controllers/ReminderController.scala, app/uk/gov/hmrc/helptosavefrontend/util/MaintenanceSchedule.scala, build.sbt, test/uk/gov/hmrc/helptosavefrontend/audit/HTSAuditorSpec.scala, test/uk/gov/hmrc/helptosavefrontend/auth/HelpToSaveAuthSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/AccessAccountControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/AccountHolderControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/AuthSupport.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/BankAccountControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ControllerSpecWithGuiceAppPerTest.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EligibilityCheckControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/EmailControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/IvControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/RegisterControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavefrontend/forms/BankDetailsValidationSpec.scala, test/uk/gov/hmrc/helptosavefrontend/forms/ReminderFrequencyValidationSpec.scala, test/uk/gov/hmrc/helptosavefrontend/models/TestData.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveReminderServiceSpec.scala, test/uk/gov/hmrc/helptosavefrontend/services/HelpToSaveServiceSpec.scala, test/uk/gov/hmrc/helptosavefrontend/util/EmailVerificationParamsSpec.scala
Address warnings created after migrating to Scala 2.13
=> DLS-6358 address warnings

app/uk/gov/hmrc/helptosavefrontend/views/helpinformation/savings_explained.scala.html, conf/messages, conf/messages.cy
https://jira.tools.tax.service.gov.uk/browse/DLS-8625
=> DLS-8625 Add help video captions

app/uk/gov/hmrc/helptosavefrontend/connectors/EmailVerificationConnector.scala, project/plugins.sbt
- removed response.body logging
- upgraded sbt-auto-build
=> DLS-6752: Addressing PII Leaks for frontend

app/uk/gov/hmrc/helptosavefrontend/views/iv/insufficient_evidence.scala.html, app/uk/gov/hmrc/helptosavefrontend/views/sign_in.scala.html
https://jira.tools.tax.service.gov.uk/browse/DLS-8921
=> DLS-8921 Fix formatting errors

app/uk/gov/hmrc/helptosavefrontend/repo/SessionStore.scala, build.sbt, conf/application.conf, project/build.properties, project/plugins.sbt, repository.yaml, test/uk/gov/hmrc/helptosavefrontend/controllers/SessionStoreBehaviourSupport.scala, test/uk/gov/hmrc/helptosavefrontend/repo/SessionStoreSpec.scala
I'm unsure of some of the changes made, requires a strict review
=> DLS-9710: Improve Session/request ID Logging
